id: P009509
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:33:46.076772
source_metadata:
  id: bdr:W8LS18619
  title: ནག་ཚང་ཤེལ་ཚཱའི་ལ་གླུ།
  author: ''
  volumes:
    aa1d3cb1b91244ecb4d0a4be0c02fce5:
      image_group_id: I8LS18621
      title: ''
      volume_number: 1
      total_pages: 181
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
